[project]
name = "03-classification"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
  "jupyter>=1.1.1",
  "jupytext>=1.17.3",
  "numpy>=2.3.3",
  "pandas>=2.3.3",
  "scikit-learn>=1.7.2",
  "seaborn>=0.13.2",
]
