[project]
name = "04-evaluation"
version = "0.1.0"
description = "evaluation metrics"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "matplotlib>=3.10.0",
]
